🐛 Fix connectivity check order of the args, pin core version to 1.4.6
rancher-sandbox/rancher-turtles pull request #123
Opened 2023-09-12 12:29 UTC by Danil-Grigorev

kind/bug

**What this PR does / why we need it**:
We need to use 1.4.4 version of CAPI for the initial release to avoid potential issues with rancher integration.
Fixes wrong argument order in cluster connectivity check.

Also adds a guide for default go.work file to make e2e tests resolvable in the current environment.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Addresses #120 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [x] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

2023-09-18 10:36 UTC, richardcase reviewed
Looks good, just the one suggestion that we use 1.4.6 as thats the latest v1.4.x release

2023-09-18 10:36 UTC, richardcase commented on test/e2e/config/operator.yaml
> +  CAPI_INFRASTRUCTURE: "docker:v1.4.4"
```suggestion
  CAPI_INFRASTRUCTURE: "docker:v1.4.6"
```

2023-09-18 10:36 UTC, richardcase commented on test/e2e/config/operator.yaml
> +  CAPI_CORE: "cluster-api:v1.4.4"
```suggestion
  CAPI_CORE: "cluster-api:v1.4.6"
```

2023-09-18 10:41 UTC, furkatgofurov7 requested changes

2023-09-18 10:41 UTC, furkatgofurov7 commented on README.md
> +To run unit tests, execute:
```suggestion
To execute the tests, use the following command:
```

2023-09-18 10:41 UTC, furkatgofurov7 commented on README.md
> +Detailed documentation on e2e tests architecture and usage could be found [here](./test/e2e/README.md#e2e-tests).
```suggestion
Detailed documentation on e2e tests architecture and usage can be found [here](./test/e2e/README.md#e2e-tests).
```

2023-09-18 12:19 UTC, furkatgofurov7 reviewed
Looks good, can we squash the commits?

2023-09-18 12:28 UTC, Danil-Grigorev commented
@furkatgofurov7 We can always merge with squash. Prow setup will do this automatically.

2023-09-18 13:44 UTC, Danil-Grigorev commented on test/e2e/config/operator.yaml
> +  CAPI_CORE: "cluster-api:v1.4.6"
We will have more then CAPD in e2e tests soon, it is better to have this included, as explicit is better then implicit, but thanks for pointing this out.

2023-09-19 08:58 UTC, furkatgofurov7 approved these changes

2023-09-19 08:59 UTC, merged